const $ = (s, el = document) => el.querySelector(s);
let LANG = localStorage.getItem('lang') || 'en';
const t = path => path.split('.').reduce((o,k) => o && o[k], UI[LANG]);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function badge(status) { return `<span class="badge demo">${esc(status)}</span>`; }
function renderServices(){const el=$('#services-grid');if(!el)return;el.innerHTML=t('services.items').map(([title,desc])=>`<article class="card"><div class="body"><h3>${esc(title)}</h3><p>${esc(desc)}</p></div></article>`).join('');}
function renderProcess(){const el=$('#process-list');if(!el)return;el.innerHTML=t('process.steps').map(([title,desc])=>`<li><h3>${esc(title)}</h3><p>${esc(desc)}</p></li>`).join('');}
function renderTeam(){const el=$('#team-grid');if(!el)return;el.innerHTML=t('team.members').map(([initial,color,name,role,bio,skills])=>`<article class="card member"><div class="avatar" style="background:${color}">${esc(initial)}</div><h3>${esc(name)}</h3><p class="role">${esc(role)}</p><p>${esc(bio)}</p><div class="chips skills">${skills.map(s=>`<span class="chip">${esc(s)}</span>`).join('')}</div></article>`).join('');}
function linkMarkup(p, detail=false){const w=t('work'), links=[];if(detail)links.push(`<a class="btn btn-ghost" href="index.html">${esc(t('back'))}</a>`);if(p.links.demo){const isVideo=p.video || /\.mp4(?:$|\?)/i.test(p.links.demo);links.push(`<a class="${detail?'btn btn-primary':''}" href="${esc(p.links.demo)}" ${isVideo?'download':''} ${isVideo?'aria-label="'+esc(w.video)+'" target="_blank"':''}>${esc(isVideo?w.video:w.demo)}${detail?' ↗':''}</a>`);}if(p.links.code)links.push(`<a class="${detail?'btn btn-ghost':''}" href="${esc(p.links.code)}" target="_blank" rel="noopener">${esc(w.code)}${detail?' ↗':''}</a>`);return links.join('');}
function projectCard(p){const w=t('work');return `<article class="card project"><a class="cover" href="project.html?p=${encodeURIComponent(p.id)}" aria-label="${esc(p.title)}" style="background:${p.image?`url('${p.image}') center/cover no-repeat`:p.cover}"><span>${esc(p.initial||p.title[0])}</span><span class="project-index">${esc(p.no||'')}</span></a><div class="body"><div class="meta">${badge(p.status)}<span class="credit">${esc(p.credit||'')}</span></div><h3>${esc(p.title)}</h3><p class="tagline">${esc(p.tagline)}</p><p class="desc">${esc(p.desc)}</p><div class="chips">${p.tech.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="links"><a href="project.html?p=${encodeURIComponent(p.id)}">${esc(w.view)}</a>${p.links.demo&&!p.video?`<a href="${esc(p.links.demo)}" target="_blank" rel="noopener">${esc(w.demo)} ↗</a>`:''}${p.video?`<a href="project.html?p=${encodeURIComponent(p.id)}">${esc(w.video)}</a>`:''}${p.links.code?`<a href="${esc(p.links.code)}" target="_blank" rel="noopener">${esc(w.code)} ↗</a>`:''}</div></div></article>`;}
function renderProjects(){const featured=$('#projects-grid'),more=$('#more-grid');if(featured)featured.innerHTML=PROJECTS.filter(p=>p.group!=='more').map(projectCard).join('');if(more)more.innerHTML=PROJECTS.filter(p=>p.group==='more').map(projectCard).join('');}
function renderProjectPage(){const root=$('#project');if(!root)return;const p=PROJECTS.find(x=>x.id===new URLSearchParams(location.search).get('p'));if(!p){location.href='index.html';return;}const w=t('work'),m=t('project');const media=p.video?`<div class="pvideo"><video controls playsinline preload="metadata" poster="${esc(p.video.poster)}"><source src="${esc(p.video.src)}" type="video/mp4">Your browser does not support HTML5 video.</video></div>`:`<div class="pcover" style="background:${p.image?`url('${p.image}') center/cover no-repeat`:p.cover}"><span>${esc(p.initial||'')}</span></div>`;const gallery=p.gallery?`<div class="gallery">${p.gallery.map(src=>`<img src="${esc(src)}" loading="lazy" alt="${esc(p.title)}">`).join('')}</div>`:'';root.innerHTML=`<a class="backlink" href="index.html">${esc(t('back'))}</a><div class="phead"><div class="meta">${badge(p.status)}<span class="credit">${esc(p.credit||'')}</span></div><h1>${esc(p.title)}</h1><p class="tagline">${esc(p.tagline)}</p></div>${media}${gallery}<p class="desc-lg">${esc(p.desc)}</p><div class="detail-grid"><article class="detail-card"><h3>${esc(m.problem)}</h3><p>${esc(p.problem||p.desc)}</p></article><article class="detail-card"><h3>${esc(m.solution)}</h3><p>${esc(p.solution||p.tagline)}</p></article></div><ul class="features">${p.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="tech-block"><div class="chips">${p.tech.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></div><div class="detail-grid"><article class="detail-card"><h3>${esc(m.status)}</h3><p>${esc(p.status)}</p></article><article class="detail-card"><h3>${esc(m.links)}</h3><div class="pactions">${linkMarkup(p,true)||'—'}</div></article></div>`;}
function setLang(lang){LANG=UI[lang]?lang:'en';localStorage.setItem('lang',LANG);document.documentElement.lang=LANG;document.documentElement.dir=LANG==='ar'?'rtl':'ltr';document.title=t('meta_title');const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=t('meta_description');document.querySelectorAll('[data-i18n]').forEach(el=>{const value=t(el.dataset.i18n);if(typeof value==='string')el.textContent=value;});document.querySelectorAll('[data-wa]').forEach(a=>a.href=`https://wa.me/21628771979?text=${encodeURIComponent(t('contact.wa_text'))}`);const toggle=$('#lang-toggle');if(toggle)toggle.textContent=LANG==='en'?'العربية':'EN';const footer=$('[data-i18n="footer"]');if(footer)footer.textContent=t('footer').replace('{year}',new Date().getFullYear());renderServices();renderProcess();renderTeam();renderProjects();if(document.body.dataset.page==='project')renderProjectPage();}
$('#lang-toggle').addEventListener('click',()=>setLang(LANG==='en'?'ar':'en'));setLang(LANG);
